language: java

matrix:
  include:
  - jdk: oraclejdk8
  allow_failures:
  - jdk: openjdk11

# skip the Travis-CI install phase because Maven handles that directly
install:
- "true"

script:
- "./mvnw install"